# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcpRc < Formula
  desc "Release-candidate builds of Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.1.0-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.2/kyverno-mcp_0.1.0-rc.2_macos_amd64.zip"
      sha256 "28953cd2db96f05437ca438cd2de0b04c4423a726b101fd3ffec54f0aede5d49"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.2/kyverno-mcp_0.1.0-rc.2_macos_arm64.zip"
      sha256 "cbf97096c1903025d01f44a76394f86fa4a131fa0215a1b0ace9cc62ed7e79eb"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.2/kyverno-mcp_0.1.0-rc.2_linux_amd64.zip"
      sha256 "3c7fd4ca370020878b65ca64637d9675aecfbabdc4f73950829a7d7b497536d1"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.2/kyverno-mcp_0.1.0-rc.2_linux_arm64.zip"
      sha256 "193af004136dcd8f17f5c5b44437d53e8682a9d47e34fb17500e1ff807261970"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  conflicts_with "kyverno-mcp"
end
