# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcpAT02 < Formula
  desc "GA release 0.2 of Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.2.0/kyverno-mcp_0.2.0_macos_amd64.zip"
      sha256 "63e9f9e2c33573ecfaf1a17f1644364574141aef87f1b278ada283b4b7b79234"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.2.0/kyverno-mcp_0.2.0_macos_arm64.zip"
      sha256 "fd3cbfe223ea3ad88c889526019f96aaa5c1d77c7b0fe1a4d1c504b21be7e104"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.2.0/kyverno-mcp_0.2.0_linux_amd64.zip"
      sha256 "df15b2f128a53fe4588569d34e2673845efa570224c94123c7294f2101400e68"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.2.0/kyverno-mcp_0.2.0_linux_arm64.zip"
      sha256 "87e71e3491e578dd388cc8090664119fcc7217308221e1bec609d6d751fc1bc9"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  conflicts_with "kyverno-mcp"
end
