# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcp < Formula
  desc "Latest Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_macos_amd64.zip"
      sha256 "7ecbd90a131a125b83b8288f4100a3623d2b8f6f7592d98830242646057b4a05"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_macos_arm64.zip"
      sha256 "94275d55d7eaf1af4a9d0bebc51a5231c820b09226d0febc036ebc97817854dc"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_linux_amd64.zip"
      sha256 "95f021b695e992ae8116a9c7a40899c33d97815bb1a0153aec84fc30caede3c2"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_linux_arm64.zip"
      sha256 "e34af9e13e5e93f44ea9b0213d8a423a21b88a5c5b167a1a2ddbae4cd824cdc4"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end
end
