# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcpRc < Formula
  desc "Release-candidate builds of Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.1.0-rc.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.7/kyverno-mcp_0.1.0-rc.7_macos_amd64.zip"
      sha256 "4da41b2868d23cfc0e48f75b9de1332c089492887fcfccbf73f9ebdaf5e738c9"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.7/kyverno-mcp_0.1.0-rc.7_macos_arm64.zip"
      sha256 "a422ac97c9d0d0e4ef7fb0376c9c7b7e67747f464d14a6e260fbbbf4a2a657e2"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.7/kyverno-mcp_0.1.0-rc.7_linux_amd64.zip"
      sha256 "1add6ca434c3d4e10b4147a26545ae0ad48715ee1ab59766afc3aaa9791d0870"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.7/kyverno-mcp_0.1.0-rc.7_linux_arm64.zip"
      sha256 "8d8e3bb3ae07331ac091f12ab798d0e06a2b966d809a6a8b0aa1b7d0754637bf"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  conflicts_with "kyverno-mcp"
end
