# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcp < Formula
  desc "Latest Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://nirmata-downloads.s3.us-east-2.amazonaws.com/kyverno-mcp/kyverno-mcp_0.2.2/kyverno-mcp_0.2.2_macos_amd64.zip"
      sha256 "2deebcada411a384cb3785672128890638ce61826b5f0c54e85eb5a07e832065"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://nirmata-downloads.s3.us-east-2.amazonaws.com/kyverno-mcp/kyverno-mcp_0.2.2/kyverno-mcp_0.2.2_macos_arm64.zip"
      sha256 "e051e489af54a60b5d0f8ec8c097c42d762e2eb6b4a35c6cbd6df82a6b7faedd"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://nirmata-downloads.s3.us-east-2.amazonaws.com/kyverno-mcp/kyverno-mcp_0.2.2/kyverno-mcp_0.2.2_linux_amd64.zip"
      sha256 "2018d2b3dec685fe2cffec6520b198e91a961f957e25b1243fe98bf741858b20"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://nirmata-downloads.s3.us-east-2.amazonaws.com/kyverno-mcp/kyverno-mcp_0.2.2/kyverno-mcp_0.2.2_linux_arm64.zip"
      sha256 "d28a49862f930098986c2798179432291741eb5df83a2e87526a6dcdbc1c45ee"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end
end
