# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcpRc < Formula
  desc "Release-candidate builds of Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.1.0-rc.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.6/kyverno-mcp_0.1.0-rc.6_macos_amd64.zip"
      sha256 "a053fce3d2ab7172605c2ba880b6665caf68a2ba7ce698d653b1a44c64ee4422"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.6/kyverno-mcp_0.1.0-rc.6_macos_arm64.zip"
      sha256 "d1b06c1c5e330f5229b4c31b19d021925cbfc72f57c7e9300ff5a1e7d75d3602"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.6/kyverno-mcp_0.1.0-rc.6_linux_amd64.zip"
      sha256 "4f700877fce5b25e324edf609125bdb82d7ff4917902bfc4adf654b459bf1a30"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0-rc.6/kyverno-mcp_0.1.0-rc.6_linux_arm64.zip"
      sha256 "a5ce5d5d38b9dfba1ef57f8570cde3fc802d895a4ac594bed85250ec6a3d16cd"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  conflicts_with "kyverno-mcp"
end
