# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcp < Formula
  desc "Latest Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_macos_amd64.zip"
      sha256 "643184a24762df0872d65336ae28903aa371e2946571ae2ebe8d0fb1165928cb"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_macos_arm64.zip"
      sha256 "163d33bd3006050f39e12429ab6384dceb85a89091ae90d630d725440c21f0f1"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_linux_amd64.zip"
      sha256 "5f639a703af6ad25ef4b9c63e3d87b72c72dfd2c7d1637a4e511ed0c764c34ec"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.0.1/kyverno-mcp_0.0.1_linux_arm64.zip"
      sha256 "88927ed38a538756ed46dc259a912b3954da5b27a3a2dc7e15b9d5b48806f7b1"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end
end
