# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KyvernoMcpAT01 < Formula
  desc "GA release 0.1 of Kyverno MCP Server"
  homepage "https://docs.nirmata.io/kyverno-mcp/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0/kyverno-mcp_0.1.0_macos_amd64.zip"
      sha256 "0ff454af80432fa2e39f22a447a0a370bb29da112fda0edeb0cabbbdfa984951"

      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0/kyverno-mcp_0.1.0_macos_arm64.zip"
      sha256 "71c1abd551c8fbd7549fbc4ea19c92ef7c57dc92eb1f00878f5cbe2466be1f08"

      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0/kyverno-mcp_0.1.0_linux_amd64.zip"
      sha256 "64e4a19a0e01b2037f07f288ee7cb0df6ce067840aba040dabb39cf1ba01b445"
      def install
        bin.install "kyverno-mcp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/kyverno-mcp/kyverno-mcp_0.1.0/kyverno-mcp_0.1.0_linux_arm64.zip"
      sha256 "82f24a549ac8bd6e373545d876b45579ceff910e28ac9929b459d6d123e60450"
      def install
        bin.install "kyverno-mcp"
      end
    end
  end

  conflicts_with "kyverno-mcp"
end
