# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT42Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.3-rc.7"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.7/nctl_4.2.3-rc.7_macos_amd64.zip"
      sha256 "5ea551353c787aa12770427d5c93411c008b5a0427f8e17e93312e5e57a22dc5"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.7/nctl_4.2.3-rc.7_macos_arm64.zip"
      sha256 "bff17c7d6acb760600fe2bf4638a96f028434e455f0b344ca2f8184e86d4dec3"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.7/nctl_4.2.3-rc.7_linux_amd64.zip"
        sha256 "e8515925361725ec13fdf2335eb57b1818c07aeb6e1b005a0c34b04ebbc9e756"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.7/nctl_4.2.3-rc.7_linux_arm64.zip"
        sha256 "bdfdc51f1710cce7f724a2d70f10ec3a5750a9f0984939e40462b454e3745311"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
