# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT410 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.10.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.10.2/nctl_4.10.2_macos_amd64.zip"
      sha256 "f7af455d0eadf36d00dce0ec5a8d716666ac25619baeffd6718af77a3fea975c"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.10.2/nctl_4.10.2_macos_arm64.zip"
      sha256 "5636dd575f65f5f20e7edcb43e13a1eeb2f2ab6dacef423eb76c438b942dd7b5"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.2/nctl_4.10.2_linux_amd64.zip"
      sha256 "fca049bd55ed6c685f90c9e5ac26b28cd42a4c57c37e6619aecf73d2bd10f0bb"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.2/nctl_4.10.2_linux_arm64.zip"
      sha256 "d216f214c2d1a7d7d3fea4abd734da1528bcb56e4b539fd22f84218df9b19698"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
