# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT410Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.10.7-rc.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.3/nctl_4.10.7-rc.3_macos_amd64.zip"
      sha256 "6401904975e44bbe1dd25a190dd1151520513531377b4cf6ca1c76efd41a6552"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.3/nctl_4.10.7-rc.3_macos_arm64.zip"
      sha256 "844ed537d0407429c0471f7c6672c3f925dbecb73998baf134c7278744216d3d"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.3/nctl_4.10.7-rc.3_linux_amd64.zip"
      sha256 "0ce2484537d9c3d9843ac801d4184a4eaa38bda1a69be76150bb235436b83053"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.3/nctl_4.10.7-rc.3_linux_arm64.zip"
      sha256 "c93dd810429430f018d288fdee15b4edf358ff993db83b046984f0ec20c97dc5"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
