# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT43Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.3.4-rc.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.3.4-rc.7/nctl_4.3.4-rc.7_macos_amd64.zip"
      sha256 "b40e2b60ebbff1888666eed41620146a3e876c9a6b64476ad395858dbae02376"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.3.4-rc.7/nctl_4.3.4-rc.7_macos_arm64.zip"
      sha256 "4d60fb5c77591e847a90dc013be71d161c97251fc728c030fa6438215ca6292f"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.3.4-rc.7/nctl_4.3.4-rc.7_linux_amd64.zip"
        sha256 "da2b4407bd393f54f48360f03c3a34dee6dc735fb9ef1fd09b4a01712c4c2303"

        def install
          bin.install "nctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.3.4-rc.7/nctl_4.3.4-rc.7_linux_arm64.zip"
        sha256 "5753c03e10c268f3b19bf6b3fd76bfb4b636adbf860c413456bed7c4056ea887"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
