# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT47Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.7.8-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.7.8-rc.2/nctl_4.7.8-rc.2_macos_amd64.zip"
      sha256 "031ec2e890e4fb5c697e4709076e87ae03d08d042d915aca4f667176423e2370"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.7.8-rc.2/nctl_4.7.8-rc.2_macos_arm64.zip"
      sha256 "18dcd3ce76663daba0f79e8e9b1caa589d698dfa70c2f62c9275579d63aae683"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.8-rc.2/nctl_4.7.8-rc.2_linux_amd64.zip"
      sha256 "c1b112c7d9381bb51aada6d218250847747b519b99b95e2cafed34e6360d84aa"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.8-rc.2/nctl_4.7.8-rc.2_linux_arm64.zip"
      sha256 "f9d0df5a87b463e752d5a5b1927342134dc244b7970ddabf1ca7db58edda0fee"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
