# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nctl < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.3"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3/nctl_4.2.3_macos_amd64.zip"
      sha256 "22f1dc3f38ea45b702a8facff984b47942688e616447e52cfc8d37eacb38cde4"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3/nctl_4.2.3_macos_arm64.zip"
      sha256 "511366bf7a54a2bd1cbdf41408a5bc9fc96e83594a1fdf8b980c079a0d33d0bb"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3/nctl_4.2.3_linux_amd64.zip"
        sha256 "713594351f2931f3dbd2d41d3a3c529259a0d2cbd48e1a587008bc5574eb2afc"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3/nctl_4.2.3_linux_arm64.zip"
        sha256 "f9d2f2dab71196c828f8c7c423e23cdd6de11a1cca8b865c0d9635c80b98a381"

        def install
          bin.install "nctl"
        end
      end
    end
  end
end
