# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT48Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.8.0-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0-rc.2/nctl_4.8.0-rc.2_macos_amd64.zip"
      sha256 "4e56b747e5664520ce4620b3ad3028a749080b3bd0adc30a18f96ffac978da09"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0-rc.2/nctl_4.8.0-rc.2_macos_arm64.zip"
      sha256 "3dcd941f6ac61e07d9d1dc398d1b2a3f1cbde693a423f084cd3991cbedb272d0"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0-rc.2/nctl_4.8.0-rc.2_linux_amd64.zip"
      sha256 "83358c206552e7ce7062d6354b870018e37a0ba7af639f217919ffd2c535ac2f"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0-rc.2/nctl_4.8.0-rc.2_linux_arm64.zip"
      sha256 "74973d687718bedab1214cb103cf964cae8ed9432f9e4f22ef141abc33c03085"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
