# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT45 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.5.1/nctl_4.5.1_macos_amd64.zip"
      sha256 "87c0b990a84405416d97ff498012140b93ec2614769bf61128faed6c2576701f"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.5.1/nctl_4.5.1_macos_arm64.zip"
      sha256 "f083e0108e234ee865a04bb587b0b91d3e37a2f894684ecab782aa8d0f8ca94e"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.5.1/nctl_4.5.1_linux_amd64.zip"
      sha256 "0e351c491dc722b7b2bccdd8169f334f47f1d5a7e1f092dcfcb4dd12830de396"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.5.1/nctl_4.5.1_linux_arm64.zip"
      sha256 "ff7ba4395fa01f62e115f982319210ba976f77ac9b94525e31fe8aef03af9443"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
