# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT48 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0/nctl_4.8.0_macos_amd64.zip"
      sha256 "e664ac47b7af2853c905fb650759be07243e2dac589dc73561274914d3bfba4b"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0/nctl_4.8.0_macos_arm64.zip"
      sha256 "6e636cda79cf49c0e7bed532c84dd59f883107cf39635d54616248bbbd85de15"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0/nctl_4.8.0_linux_amd64.zip"
      sha256 "465261add4c6557e7bebb5bd9ef9b7dfb3773cb000bb73a0c1bf7c89fe735e2d"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.8.0/nctl_4.8.0_linux_arm64.zip"
      sha256 "18b7a0bf5b42024e4d293be6ed6350c15fffedb3830af3f1261a795fc9ed925f"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
