# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT44Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.4.0-rc.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.5/nctl_4.4.0-rc.5_macos_amd64.zip"
      sha256 "30584bf70378f4bd8478a740e5a7f3177c1ee74f0918606c258aedaa5aaff5b9"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.5/nctl_4.4.0-rc.5_macos_arm64.zip"
      sha256 "ed1f8f8c00fa59433dc4f28376d9adc1850db4d59204dc8f12ff19d00afe4e6d"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.5/nctl_4.4.0-rc.5_linux_amd64.zip"
        sha256 "a6258ccc6ba1874185d9fc20137b7e0e6f8b17eb8562a03b790cebf8d7234f92"

        def install
          bin.install "nctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.5/nctl_4.4.0-rc.5_linux_arm64.zip"
        sha256 "7ad34e592812f9c2651db317dcd4e53888ac0ba96db3655ed160696b497e62f9"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
