# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT42Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.4-rc.1"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.2.4-rc.1/nctl_4.2.4-rc.1_macos_amd64.zip"
      sha256 "90e01f9af3512188161a39df95aa9b8410e135ea19a1b44611eb99cf2eae30a8"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.2.4-rc.1/nctl_4.2.4-rc.1_macos_arm64.zip"
      sha256 "786b7e344ae5ecce01a9abd2d0ac48263e4b702b6b12224f34ba259d272d6799"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.4-rc.1/nctl_4.2.4-rc.1_linux_amd64.zip"
        sha256 "b62a5b7a50241a140ccbfb9a513e4b2d9ead739d51ff580ec881e2209b0b4fed"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.4-rc.1/nctl_4.2.4-rc.1_linux_arm64.zip"
        sha256 "4b59d98fc9283cebc543a4a0833e5070754038df240f2f1ac066515deccf87b2"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
