# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nctl < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.2.10/nctl_4.2.10_macos_amd64.zip"
      sha256 "14f6605d0371485b7ca13e2834b50da6cc61cf06a8cc84106f8f6e179c93a2ab"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.2.10/nctl_4.2.10_macos_arm64.zip"
      sha256 "46eb20d7c997be70745973ad914289cccca872c95fc196310142cefc30d1200e"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.2.10/nctl_4.2.10_linux_amd64.zip"
      sha256 "ac51b1133e083abb2b03b89ebeeade7241c416a6d5a39cb00ddd4b1eb157ba76"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.2.10/nctl_4.2.10_linux_arm64.zip"
      sha256 "2b650165d09ed23e7cb6b6ba2ca9a26a8130b8e9d66e557d29ba03ce9f09ffea"
      def install
        bin.install "nctl"
      end
    end
  end
end
