# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT42Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.3-rc.6"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.6/nctl_4.2.3-rc.6_macos_amd64.zip"
      sha256 "8da1d0ce926572c6069ab25590144e6c54a71f9b7259aadb905be9e7c3f1f667"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.6/nctl_4.2.3-rc.6_macos_arm64.zip"
      sha256 "5fc69e5e4c738be9a4a52355d252c884483936faf22f203d8ace24892b3ff64a"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.6/nctl_4.2.3-rc.6_linux_amd64.zip"
        sha256 "1d5b3501786fc1a5a0ce11e6badd048e8e737fc6401581aad1f4c396174185f4"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.6/nctl_4.2.3-rc.6_linux_arm64.zip"
        sha256 "46f2223cd6e0ea935311b22f0624ff255803e4b65536f2c565669479728b8dbe"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
