# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT43Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.3.0-rc.1"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.3.0-rc.1/nctl_4.3.0-rc.1_macos_amd64.zip"
      sha256 "bac55889bae7e04058d73d26103018ee4f16b0f4eb7bb433acd88dbfe8b47dd2"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.3.0-rc.1/nctl_4.3.0-rc.1_macos_arm64.zip"
      sha256 "2264c18c4f4b8444d0bdc85f4e198f3e28199524bf9aba9853a62e680a351798"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.3.0-rc.1/nctl_4.3.0-rc.1_linux_amd64.zip"
        sha256 "57f46bc1c69990596f3d4c5bdfe043ef34fa060ceae903783a56c1f332773468"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.3.0-rc.1/nctl_4.3.0-rc.1_linux_arm64.zip"
        sha256 "e80ce6c0842d95a387e0964922bb53682787205dd074ae36dd4beaa7232022ea"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
