# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT44Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.4.0-rc.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.7/nctl_4.4.0-rc.7_macos_amd64.zip"
      sha256 "d63fa5c9164f2201d142f3486c270bb6b38f62da49791bdfe75c1e5c8cf0e61e"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.7/nctl_4.4.0-rc.7_macos_arm64.zip"
      sha256 "ce8b4a1ed45ec363554d0b48bc8f19f34f7a0261ef29e486deaa0c7ef72547f8"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.7/nctl_4.4.0-rc.7_linux_amd64.zip"
        sha256 "648ad4f4d988b874b1680b0c31217931274dd346360075578b19b826797fc9c4"

        def install
          bin.install "nctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.0-rc.7/nctl_4.4.0-rc.7_linux_arm64.zip"
        sha256 "334cfc2ed5acbb23d0be587de0b53b9cbd4270f0f80f1402de77331506e6007b"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
