# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT410Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.10.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.10.0-rc.1/nctl_4.10.0-rc.1_macos_amd64.zip"
      sha256 "89f108cc2990daf2f5701debba30d77d8b67f137a253f0363b6dbc648263b03f"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.10.0-rc.1/nctl_4.10.0-rc.1_macos_arm64.zip"
      sha256 "749596c56e50233bd710966c75b663fdf6fceeda9e8513cddddc6ec5488d8850"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.0-rc.1/nctl_4.10.0-rc.1_linux_amd64.zip"
      sha256 "8623aa72f3c4e0d53eb137d62c6d894cd95c2fa17806f47e16ce02f3f9a447b4"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.0-rc.1/nctl_4.10.0-rc.1_linux_arm64.zip"
      sha256 "10a8bce0ec46cb488ef593a6967a51cc5940730b0c1deac8eef178393b940294"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
