# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT47 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.7.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.7.9/nctl_4.7.9_macos_amd64.zip"
      sha256 "82771a8013393bcfbbf7a607132e2c0d35fe22143af5d12d17433343df82d8f3"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.7.9/nctl_4.7.9_macos_arm64.zip"
      sha256 "0ce49a1340be497fadac1c5938348c18b3bc3332c6e81c18e292c3bcdd558b7c"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.9/nctl_4.7.9_linux_amd64.zip"
      sha256 "ea17ba75565bcc660fae1d1f7704f1f5e27343267af26aed7bd9ff1f14ed2fbb"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.9/nctl_4.7.9_linux_arm64.zip"
      sha256 "d64be60e80e47bcf2f9691fc02b03baaa6079a3ea595cd103908e71ce180880e"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
