# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT410 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.10.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.10.4/nctl_4.10.4_macos_amd64.zip"
      sha256 "f7fcedcfde0821976399081508a2b784ea7192e7c59fc064669c28fd953102b6"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.10.4/nctl_4.10.4_macos_arm64.zip"
      sha256 "5be88928918c0954f2f76d429914f9b6b295509dc6a5f2003e5bba3c0fffd45a"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.4/nctl_4.10.4_linux_amd64.zip"
      sha256 "3b4bf15e26f95f884cd1a1e06ea9e924bb8300e174d93b761e5b43863eb81848"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.4/nctl_4.10.4_linux_arm64.zip"
      sha256 "22265474562c8f64b29d1775c6b9ba99a6701e3914c69197611a4e66ef630a74"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
