# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT47 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.7.0/nctl_4.7.0_macos_amd64.zip"
      sha256 "a246dc7fe3cd863903404f3e86c1171f2c1f071eb8bd02be55e82d2585d87762"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.7.0/nctl_4.7.0_macos_arm64.zip"
      sha256 "baaf514be04674ab34cad5fc7bb8fe5f3a91f692082be5a8b6612205f320cbb5"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.0/nctl_4.7.0_linux_amd64.zip"
      sha256 "ad48c5b863804e02f310c6d376c6efa4ef844517327fb0df1cea4cb06dbd63b4"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.0/nctl_4.7.0_linux_arm64.zip"
      sha256 "2a4ca10cac14044d823cde41e77ed5041c485ed5d44ffc3e86d81bc9bee1bd7e"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
