# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT410Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.10.7-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.2/nctl_4.10.7-rc.2_macos_amd64.zip"
      sha256 "d17e31be76988d2d6ecd83f1ad078e9700a17f8337015ce1e84f1ad0242b1857"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.2/nctl_4.10.7-rc.2_macos_arm64.zip"
      sha256 "84019ae8388a184827a2af5d740c3191a188062ef3c423ff912cbe3b1ab8e4b2"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.2/nctl_4.10.7-rc.2_linux_amd64.zip"
      sha256 "8c8fc1278ce7abd7276764d227800bc92ef6a852ec096688b07177da0339c64d"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.10.7-rc.2/nctl_4.10.7-rc.2_linux_arm64.zip"
      sha256 "82a50cfd5015465970bf08a3ba3a77eeb9314bc2cf35e4086c161cdf31af788e"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
