# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT424 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.24.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.24.5/nctl_4.24.5_macos_amd64.zip"
      sha256 "c7f8f18d4d64af52394dea3459ea4681eb72a3c03f9189ff6c3f02fc1c674f7a"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.24.5/nctl_4.24.5_macos_arm64.zip"
      sha256 "c440c9c5a73ae5294519f6a17cc6ea3fefa61902baa1652f4768220e099a94e1"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.24.5/nctl_4.24.5_linux_amd64.zip"
      sha256 "d6795f5366158916da2d35dd59b6b756df0e6bf33f2bb992c04e2c0dd46d5f02"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.24.5/nctl_4.24.5_linux_arm64.zip"
      sha256 "9fa937f4d055d3d693cb4514637df0bcd9f7a4fed7eeb266a2bd0218ce3ff49c"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
