# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT47Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.7.3-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.7.3-rc.1/nctl_4.7.3-rc.1_macos_amd64.zip"
      sha256 "1ad9b581d6df9024892ba81e209f5a4002bece27fb6c4549c2ba4155a9d4c433"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.7.3-rc.1/nctl_4.7.3-rc.1_macos_arm64.zip"
      sha256 "4d08abff2618cffea9972edceb52e71df1b32b494fca1498104804587eac2e43"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.3-rc.1/nctl_4.7.3-rc.1_linux_amd64.zip"
      sha256 "01cfde121797605944b62881fb42cde13487e51d89a6e8c0a22ad6fcc573c15e"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.3-rc.1/nctl_4.7.3-rc.1_linux_arm64.zip"
      sha256 "fd61533cea572577e2ccd0e9afaac8f71ad8de116e5ed764602153575a1ea83e"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
