# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT43 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.3.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.3.7/nctl_4.3.7_macos_amd64.zip"
      sha256 "da4b9de5fc29712957850875c23059f4eeba593d47baebbd909798ea3a454d10"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.3.7/nctl_4.3.7_macos_arm64.zip"
      sha256 "f0d93d2e56f05e9e23e21bdd4b4e865dc1d5de3c0248f9af810b134746cf39b3"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.3.7/nctl_4.3.7_linux_amd64.zip"
      sha256 "9b3b0e9b962f3ca1518025e6bd549eae73b2a675de45c27dfa67934a05b17e12"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.3.7/nctl_4.3.7_linux_arm64.zip"
      sha256 "67e31841748d34e62eaae2094ae3a661f655b7bff5e0d483b383048c31d09550"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
