# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT44Rc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.4.1-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.4.1-rc.1/nctl_4.4.1-rc.1_macos_amd64.zip"
      sha256 "7df28075b7b8d045bdd0555865820790a6d7c2864c5c8e0e673f183efbf41711"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.4.1-rc.1/nctl_4.4.1-rc.1_macos_arm64.zip"
      sha256 "cb83b8d4c141d366f7d04425a649c881a61077a6f711c568830f71d5c038478f"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.1-rc.1/nctl_4.4.1-rc.1_linux_amd64.zip"
        sha256 "84f0159b126699bd167cdf9cd06595d80c3455d21307caa7f2df36463812a8b3"

        def install
          bin.install "nctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.4.1-rc.1/nctl_4.4.1-rc.1_linux_arm64.zip"
        sha256 "fd51faa85db83e693b21615d13d06c86ddc4394754cb09a23ce4552158cf450a"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
