# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT46Rc < Formula
  desc "RC releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.6.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.6.0-rc.1/nctl_4.6.0-rc.1_macos_amd64.zip"
      sha256 "dce38310246ce9946d2504ea646c2c42ce0cf30e2474e200b9fa4289e1f7aac3"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.6.0-rc.1/nctl_4.6.0-rc.1_macos_arm64.zip"
      sha256 "4383570b0862c856dad08e653a44906a3fcb99b72bc0755568121d674344aae7"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.6.0-rc.1/nctl_4.6.0-rc.1_linux_amd64.zip"
        sha256 "68bae2667e6ca0d4802b0b4a8710e83cd1fb77ee5688836b8f71daf234ad19bf"

        def install
          bin.install "nctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.6.0-rc.1/nctl_4.6.0-rc.1_linux_arm64.zip"
        sha256 "aaf10ebcf9db2aa79aa2d95cb0e25dbd3040dfd4bcfad318b1f252a5fe20371a"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
