# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlATRc < Formula
  desc "Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.2.3-rc.5"

  on_macos do
    on_intel do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.5/nctl_4.2.3-rc.5_macos_amd64.zip"
      sha256 "bd7f935144154c997b955ad4ea1c978228c934c62408531a25701b5080405c78"

      def install
        bin.install "nctl"
      end
    end
    on_arm do
      url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.5/nctl_4.2.3-rc.5_macos_arm64.zip"
      sha256 "638500727862daa8db222e75d003727a2be10209ed72688beea4976aeab3b46d"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.5/nctl_4.2.3-rc.5_linux_amd64.zip"
        sha256 "52c998ddc320f1039cb1b2f3777314cdb1fdec67a73f88632b60dc74d97657f6"

        def install
          bin.install "nctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dl.nirmata.io/nctl/nctl_4.2.3-rc.5/nctl_4.2.3-rc.5_linux_arm64.zip"
        sha256 "ed12b8af79b9d9eca0cbe321a13f2b7834cb258dd9e7b08bd3d67e9e40331856"

        def install
          bin.install "nctl"
        end
      end
    end
  end

  conflicts_with "nctl"
end
