# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NctlAT47 < Formula
  desc "GA releases for the Nirmata CLI to scan and remediate Kubernetes manifests, Terraform, and more!"
  homepage "https://docs.nirmata.io/nctl/"
  version "4.7.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.nirmata.io/nctl/nctl_4.7.4/nctl_4.7.4_macos_amd64.zip"
      sha256 "41d181ef37dfc013b60dda3d710098adb180be4998d4a13c4953e7f20c3bc5c6"

      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.nirmata.io/nctl/nctl_4.7.4/nctl_4.7.4_macos_arm64.zip"
      sha256 "908043bc4c0c26ee54b73cb7dee942a6a494f01f122bb865326848a5ac7ae40f"

      def install
        bin.install "nctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.4/nctl_4.7.4_linux_amd64.zip"
      sha256 "02a210597951209e04423d85d0d451d43b376960e456bf2c917d8dcde5fce4fe"
      def install
        bin.install "nctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.nirmata.io/nctl/nctl_4.7.4/nctl_4.7.4_linux_arm64.zip"
      sha256 "49956fda42e67ccb849b2f6157c9e31bd9e4adf53b3605648b99ea734f825c36"
      def install
        bin.install "nctl"
      end
    end
  end

  conflicts_with "nctl"
end
