# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OttoflowRc < Formula
  desc "Release-candidate builds of the OttoFlow CLI"
  homepage "https://github.com/nirmata/ottoflow"
  version "5.0.0-rc.1"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nirmata/ottoflow/releases/download/v5.0.0-rc.1/ottoflow_5.0.0-rc.1_darwin_amd64.tar.gz"
      sha256 "83b6da7ea6e1f6a433f27a807dbbea864b5f2a6d9ad4391cfcd4d6fc86f4b75d"

      define_method(:install) do
        bin.install "ottoflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nirmata/ottoflow/releases/download/v5.0.0-rc.1/ottoflow_5.0.0-rc.1_darwin_arm64.tar.gz"
      sha256 "9a15189b66f7dd2cdfe52e805a00a6e0e963fab1df8f8617ee472ed4507c7cc6"

      define_method(:install) do
        bin.install "ottoflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nirmata/ottoflow/releases/download/v5.0.0-rc.1/ottoflow_5.0.0-rc.1_linux_amd64.tar.gz"
      sha256 "984f5b33af892c2c1d3b344c6b9e124056dc0d8172c05d1e6317886a3d5733dd"
      define_method(:install) do
        bin.install "ottoflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nirmata/ottoflow/releases/download/v5.0.0-rc.1/ottoflow_5.0.0-rc.1_linux_arm64.tar.gz"
      sha256 "40ecb65e0046493a91a6814b125e2c3e173e8d1b7533671d8e735476532498ad"
      define_method(:install) do
        bin.install "ottoflow"
      end
    end
  end

  conflicts_with "ottoflow"

  test do
    system "#{bin}/ottoflow", "--help"
  end
end
