# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ottoflow < Formula
  desc "Kubernetes-native workflow engine CLI"
  homepage "https://github.com/nirmata/ottoflow"
  version "0.0.1"
  license "BUSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nirmata/ottoflow/releases/download/v0.0.1/ottoflow_0.0.1_darwin_amd64.tar.gz"
      sha256 "1c671d2b04eaf40fb9cff469db212ef31758ab4cb4bdde9fef6d2df42e5a314f"

      define_method(:install) do
        bin.install "ottoflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nirmata/ottoflow/releases/download/v0.0.1/ottoflow_0.0.1_darwin_arm64.tar.gz"
      sha256 "5ba5777007070c03a729385ccf791f4530e229692f3b1f05a0acd546c4605059"

      define_method(:install) do
        bin.install "ottoflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nirmata/ottoflow/releases/download/v0.0.1/ottoflow_0.0.1_linux_amd64.tar.gz"
      sha256 "cb54605cf5ff4dcee0239529504d03bd671a44fbfdf5486d605fd6ea6e6c515f"
      define_method(:install) do
        bin.install "ottoflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nirmata/ottoflow/releases/download/v0.0.1/ottoflow_0.0.1_linux_arm64.tar.gz"
      sha256 "f097b9f104c561d5fc3b2ce8242b95ab3a7fdf03ea87bd6c6193f458e3ff3b73"
      define_method(:install) do
        bin.install "ottoflow"
      end
    end
  end

  test do
    system "#{bin}/ottoflow", "--help"
  end
end
